#!/bin/sh

# Set these paths appropriately

BIN="/Users/lilihuan/Desktop/comp4920/project/ProjectDragonfly/treetagger/bin"
CMD="/Users/lilihuan/Desktop/comp4920/project/ProjectDragonfly/treetagger/cmd"
LIB="/Users/lilihuan/Desktop/comp4920/project/ProjectDragonfly/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
