#!/bin/sh

# Set these paths appropriately

BIN="/Users/lilihuan/Desktop/comp4920/project/ProjectDragonfly/treetagger/bin"
CMD="/Users/lilihuan/Desktop/comp4920/project/ProjectDragonfly/treetagger/cmd"
LIB="/Users/lilihuan/Desktop/comp4920/project/ProjectDragonfly/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
