#!/bin/sh

# Set these paths appropriately

BIN="/Users/lilihuan/Desktop/comp4920/project/ProjectDragonfly/treetagger/bin"
CMD="/Users/lilihuan/Desktop/comp4920/project/ProjectDragonfly/treetagger/cmd"
LIB="/Users/lilihuan/Desktop/comp4920/project/ProjectDragonfly/treetagger/lib"

TOKENIZER=${BIN}/separate-punctuation
SPLITTER=${CMD}/portuguese-splitter.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/portuguese-abbreviations
POST_TAGGING=${CMD}/portuguese-post-tagging
PARFILE=${LIB}/portuguese.par

# splitting 
$SPLITTER $* |
# pre-tokenization
sed "s/\([\)\"\'\?\!]\)\([\.\,\;\:]\)/ \1 \2/g" |
# tokenizing
$TOKENIZER +1 +s +l $ABBR_LIST |
# remove empty lines
grep -v '^$' |
# tagging
$TAGGER $PARFILE -token -lemma -sgml | 
$POST_TAGGING -no
