#!/bin/sh

# Set these paths appropriately

BIN="/Users/lilihuan/Desktop/comp4920/project/ProjectDragonfly/treetagger/bin"
CMD="/Users/lilihuan/Desktop/comp4920/project/ProjectDragonfly/treetagger/cmd"
LIB="/Users/lilihuan/Desktop/comp4920/project/ProjectDragonfly/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/swahili-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
